version = 1

[image]

[image.loading]
# Setting this to "true" will make the image load on a separate thread to the GUI initially. This
# means the GUI may load up before the image is ready to display itself. Will this improve load times? idk 🤷
initial.lazy_loading = false

# Lazy loading but this is now for when you open and load an image from the GUI.
# For example: Picking an image from the file picker or dropping an image into the window.
gui.lazy_loading = true

# Setting this to "false" will make dynamic sampling reload images on the main thread. It's not 
# recommended to set this to "false" as it will lead to the GUI freezing each time you try to zoom in/out.
dynamic.lazy_loading = true

[image.optimizations]
# Comment this out if you would like to customize the optimization settings below.
# MOTE: The optimizations that are defaulted to in "mode" will always take priority over 
# the optimizations specified below.
mode = "default"

# Downsamples the image roughly to the resolution of your monitor.
# 
# Images don't always have to be displayed at their full native resolution, especially when 
# the image is significantly bigger than your monitor can even display, so to save memory 
# we downsample the image. Downsampling decreases the amount of memory eaten up by the image 
# at the cost of CPU time wasted actually resizing the image. The bigger the image the more time 
# it will take to downsample but we think memory savings are more valuable in this circumstance.
# 
# If you do not wish for such memory savings and you prefer faster image load time disable 
# this optimization.
# 
# If you want your image quality back when zooming into your image, 
# you might want to also enable the "dynamic_sampling" image optimization too.
monitor_downsampling = {enabled = true, strength = 1.3}

[ui]

[ui.magnification_panel]
# Setting this to "true" will enable the magnification panel by default.
enabled_default = false

[ui.viewport]
# Adjust this value to control the spacing between the image and the edge of the window.
padding = 2

[key_binds]
info_box.toggle = "I"
about_box.toggle = "A"
# Keybind to reset the image pan 
# position and zoom scale back to default.
image.reset_pos = "R"
# Keybind to toggle all your UI controls like the magnification panel.
ui_controls.toggle = "C"

[misc]
# All other configs that don't yet have a specific place or are experimental.
# Configs here will be moved or removed without further notice.

# override_monitor_size = {width = 1920, height = 1080}

[misc.experimental]
# Settings to toggle experimental features that aren't yet ready yet to be 
# used by the wider user audience. This exists for the sole purpose of testing.
# 
# Remember these are EXPERIMENTAL, bugs WILL be present.

# Setting this to "zune-image" will use zune-image to decode images WHICH IS VERY EXPERIMENTAL 
# and will enable the experimental lanczos Roseate image processing backend for downsampling 
# which is faster than the image-rs backend but may result in buggy / blocky images.
# 
# Set this back to it's default, "image-rs" if the image looks weird or you want stability.
image_processing_backend = "image-rs"

# Setting this to true will enable the new but extremely experimental 
# dynamic sampling feature that upsamples your image when you zoom into it 
# to bring back the detail lost from monitor downsampling.
# 
# If this feature was more complete it would live under "[image.optimizations]"
# as "dynamic_sampling = {enabled = false, also_downsample = true}".
# 
# Again, this is VERY experimental and incomplete! Expect a very broken implementation.
use_dynamic_sampling_optimization = false