name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-zip:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: roseate
          target: ${{ matrix.target }}
          include: ./LICENSE
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
  
  inno-installer:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build Roseate
        run: cargo build --release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: assets/roseate.iss
          options: /O+ /version=${{ github.ref_name }}

      - name: Upload Setup
        env:
            GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} .\assets\Output\roseate-setup.exe